name: my first workflow example
on: push
jobs:
    say hello:
        name: abid hello
        runs-on: ubuntun-22.04
        steps:
            - name: Greeting the actions
              run: echo "heloo abid"